sudo: required
services:
  - docker 

before_install:
  - docker build -t jeremybjohnson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeremybjohnson/react-test npm test

after_success: 
  - docker build -t jeremybjohnson/multi-client ./client
  - docker build -t jeremybjohnson/multi-nginx ./nginx
  - docker build -t jeremybjohnson/multi-server ./server
  - docker build -t jeremybjohnson/multi-worker ./worker
  # login to docker cli
  # travis cli specific code to login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push jeremybjohnson/multi-client
  - docker push jeremybjohnson/multi-worker
  - docker push jeremybjohnson/multi-nginx
  - docker push jeremybjohnson/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-east-1-126609397906
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  